
export const ADD_NEW_DATA = "ADD_NEW_DATA"
export const FETCH_DATA = "FETCH_DATA"
export const SAVE_DATA_EDIT = "SAVE_DATA_EDIT"
export const SAVE_DISPLAY_FORM = "SAVE_DISPLAY_FORM"
export const SAVE_ACTION = "SAVE_ACTION"